#!/usr/bin/python3
#
# xyes program

import sys

def args_contains_limit(args):
  return len(args) >= 2 and args[1] == '-limit'

def get_limit(args):
  if args_contains_limit(args):
    return 20
  else:
   return -1

def get_message(args):
  if args_contains_limit(args):
    message = ' '.join(args[2:])
  else:
    message = ' '.join(args[1:])

  if not message:
    return 'hello world'
  return message

def run(message, limit):  
  while (limit > 0 or limit == -1):
    print(message)
    if limit > 0:
      limit -= 1

args = sys.argv
run(get_message(args), get_limit(args))























