#!/usr/bin/python3

import sys
import json

input_string = sys.stdin.read()

decoder = json.JSONDecoder()

elements = []
position = 0

while position != len(input_string):
    before_len = len(input_string[position:])
    after_len = len(input_string[position:].strip())
    if after_len == 0:
        break
    spaces_removed = before_len - after_len

    json_elem, json_len = decoder.raw_decode(input_string[position:].strip())

    position +=(json_len + spaces_removed)
    elements.append(json_elem)

output1 = {"count" : len(elements), "seq" : elements}
output2 = [len(elements)]
output2 += reversed(elements)

print(json.dumps(output1))
print(json.dumps(output2))

