#!/usr/bin/python3
import sys
sys.path.append('..')
import json
from Fish.Common.board import Board



def read_json():
    input_string = sys.stdin.read()

    decoder = json.JSONDecoder()

    elements = []
    position = 0

    while position != len(input_string):
        before_len = len(input_string[position:])
        after_len = len(input_string[position:].strip())
        if after_len == 0:
            break
        spaces_removed = before_len - after_len

        json_elem, json_len = decoder.raw_decode(input_string[position:].strip())

        position += (json_len + spaces_removed)
        elements.append(json_elem)
    return elements


def get_num_moves(json):
    pos = tuple(json["position"])
    layout = json["board"]
    rows = len(layout)
    cols = len(layout[0])

    # Convert format used for testing into our format of a board.
    for x in range(len(layout)):
        for y in range(len(layout[x])):
            if layout[x][y] == 0:
                layout[x][y] = -1

    board = Board(rows, cols, layout=layout)
    return len(board.get_valid_moves(pos))



if __name__ == "__main__":
    json = read_json()[0]
    num = get_num_moves(json)
    print(num)
