#!/usr/bin/python3

import socket
import sys

PORT = int(sys.argv[1])

serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
serversocket.bind((socket.gethostname(), PORT))
serversocket.listen(1)

(clientsocket, address) = serversocket.accept()




def parse_json(input_string):
  elements = []
  position = 0

  while position != len(input_string):
    before_len = len(input_string[position:])
    after_len = len(input_string[position:].strip())
    if after_len == 0:
        break
    spaces_removed = before_len - after_len

    json_elem, json_len = decoder.raw_decode(input_string[position:].strip())

    position +=(json_len + spaces_removed)
    elements.append(json_elem)

  return elements