#!/usr/bin/python3

import socket
import sys
import json


def parse_json(input_string):
  elements = []
  position = 0
  decoder = json.JSONDecoder()

  while position != len(input_string):
    before_len = len(input_string[position:])
    after_len = len(input_string[position:].strip())
    if after_len == 0:
        break
    spaces_removed = before_len - after_len

    json_elem, json_len = decoder.raw_decode(input_string[position:].strip())

    position +=(json_len + spaces_removed)
    elements.append(json_elem)

  return elements

PORT = int(sys.argv[1])

serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
serversocket.settimeout(60)
serversocket.bind(("localhost", PORT))
serversocket.listen(1)

(clientsocket, address) = serversocket.accept()


chunks = []
while True:
  data = clientsocket.recv(4096)
  if not data:
    break
  chunks.append(data.decode("utf-8"))

results = parse_json("".join(chunks))

output1 = {"count" : len(results), "seq" : results}
output2 = [len(results)]
output2 += reversed(results)

clientsocket.send(str(output1).encode())
clientsocket.send(str(output2).encode())

serversocket.close()
clientsocket.close()