#!/usr/bin/python3
import pathlib
import sys
scriptPath = pathlib.Path(__file__).parent.absolute()
sys.path.append(str(scriptPath / ".."))

from Fish.Remote.server import Server

if __name__ == "__main__":
    pass