state_type: multi-agent
config:
  min_players: 2
  max_players: 3
  player_colors: 
    - red
    - brown
    - gray
    - black
  board:
    board_type: fish
    config:
      layout: 
        uniform: 3