state_type: multi-agent
config:
  board_type: fish
  config:
    min_players: 2
    max_players: 3
    player_colors: 
      - red
      - brown
      - white
      - black
    layout: 
      uniform: 3