#!/usr/bin/python
import Tkinter
import sys


def main(args):
    if len(args) != 2:
        print("Usage:   ./xgui positive-integer")
        return
    try:
        size = int(args[1])
        if size <= 0:
            print("Usage:   ./xgui positive-integer")
            return
    except:
        print("Usage:    ./xgui postive_integer")
        return
    draw_hexagon(size)



if __name__ == '__main__':
    args = sys.argv
    main(args)

