#!/usr/bin/python
from Tkinter import *
#from Tkinter.ttk import *
import sys

class Hexagon:
    def __init__(self, size, master=None):
        self.master = master
        self.size = size

    def create(self):
        self.canvas = Canvas(self.master, bg="white", width=self.size*3.5, height=self.size*3.5)
        self.get_points()
       
        self.canvas.create_polygon(self.points, outline="red", fill="white", width=2, tags="hexagon")
        
        self.canvas.tag_bind("hexagon", "<Button-1>", self.clicked)
       
        self.canvas.pack()

    def get_points(self):
        self.points = [self.size, 1, 
                2*self.size, 1, 
                3*self.size, self.size+1, 
                2*self.size, 2*self.size+1,
                self.size, 2*self.size+1,
                0, self.size+1]
        return self.points

    def clicked(self, *args):
        exit(0)

def get_size_from_args(args)
    if len(args) != 2:
        return "Usage:   ./xgui positive-integer"
    else:
        try:
            size = int(args[1])
            if size <= 0:
                return "Usage:   ./xgui positive-integer"
            elif size > 300:
                return "Error:   Size must be between 1 and 300"
            else:
                return size
        except ValueError:
            return "Usage:    ./xgui postive_integer"


def main(args):
    size = get_size_from_args(args)
    
    if typeof(size) == "str":
      print size
      exit(1)

    master = Tk()
    hexagon = Hexagon(size, master=master)
    hexagon.create()

    #master.title("D")
    #master.geometry("{:.0f}x{:.0f}".format(size*3.5, size*3.5))
    mainloop()



if __name__ == '__main__':
    args = sys.argv
    main(args)

